/* Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * C operand-type table for HIR instructions.
 * Phase 3: replaces C++ _OperandTypes mixin dispatch.
 * Generated from DEFINE_SIMPLE_INSTR/INSTR_CLASS macro args in hir.h.
 */

#include "cinderx/Jit/hir/hir_operand_types_c.h"
#include "cinderx/Jit/hir/hir_instr_c.h"  /* for HIR_CONSTRAINT_k* enum values */

/* Shorthand for common operand type patterns */
#define OT(ty)    {HIR_CONSTRAINT_kType, ty}   /* Type constraint */
#define OC(c)     {c, HIR_TYPE_BOTTOM}         /* Non-type constraint */

static const HirOpcodeOperandInfo operand_type_table[] = {
    /* Assign                                   */ {1, {OT(HIR_TYPE_TOP)}},
    /* BatchDecref                              */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* BeginInlinedFunction                     */ {0, {{0}}},
    /* BinaryOp                                 */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* BitCast                                  */ {1, {OT(HIR_TYPE_TOP)}},
    /* Branch                                   */ {0, {{0}}},
    /* BuildSlice                               */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* BuildString                              */ {1, {OT(HIR_TYPE_UNICODE)}},
    /* BuildInterpolation                       */ {3, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* BuildTemplate                            */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* CallCFunc                                */ {1, {OT(HIR_TYPE_OPTOBJECT_OR_CUINT64)}},
    /* CallEx                                   */ {3, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* CallIntrinsic                            */ {1, {OT(HIR_TYPE_OPTOBJECT_OR_CUINT64)}},
    /* CallInd                                  */ {1, {OT(HIR_TYPE_TOP)}},
    /* CallMethod                               */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* CallStatic                               */ {1, {OT(HIR_TYPE_TOP)}},
    /* CallStaticRetVoid                        */ {1, {OT(HIR_TYPE_TOP)}},
    /* Cast                                     */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* CheckSequenceBounds                      */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_CINT)}},
    /* CheckErrOccurred                         */ {0, {{0}}},
    /* CheckExc                                 */ {1, {OC(HIR_CONSTRAINT_kOptObjectOrCInt)}},
    /* CheckNeg                                 */ {1, {OT(HIR_TYPE_CINT)}},
    /* CheckVar                                 */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* CheckFreevar                             */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* CheckField                               */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* CIntToCBool                              */ {1, {OT(HIR_TYPE_CINT64)}},
    /* Compare                                  */ {2, {OT(HIR_TYPE_OPTOBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* CompareBool                              */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* ConvertValue                             */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* CopyDictWithoutKeys                      */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_TUPLEEXACT)}},
    /* CondBranch                               */ {1, {OC(HIR_CONSTRAINT_kOptObjectOrCIntOrCBool)}},
    /* CondBranchIterNotDone                    */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* CondBranchCheckType                      */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* Decref                                   */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* DeleteAttr                               */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* DeleteSubscr                             */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* Deopt                                    */ {0, {{0}}},
    /* DeoptPatchpoint                          */ {0, {{0}}},
    /* DictMerge                                */ {3, {OT(HIR_TYPE_DICT), OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* DictSubscr                               */ {2, {OT(HIR_TYPE_DICTEXACT), OT(HIR_TYPE_OBJECT)}},
    /* DictUpdate                               */ {2, {OT(HIR_TYPE_DICT), OT(HIR_TYPE_OBJECT)}},
    /* DoubleBinaryOp                           */ {2, {OT(HIR_TYPE_CDOUBLE), OT(HIR_TYPE_CDOUBLE)}},
    /* EagerImportName                          */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_LONG)}},
    /* EndInlinedFunction                       */ {0, {{0}}},
    /* FillTypeAttrCache                        */ {1, {OT(HIR_TYPE_TYPE)}},
    /* FillTypeMethodCache                      */ {1, {OT(HIR_TYPE_TYPE)}},
    /* FloatBinaryOp                            */ {2, {OT(HIR_TYPE_FLOATEXACT), OT(HIR_TYPE_FLOATEXACT)}},
    /* FloatCompare                             */ {2, {OT(HIR_TYPE_FLOATEXACT), OT(HIR_TYPE_FLOATEXACT)}},
    /* FormatValue                              */ {2, {OT(HIR_TYPE_OPTUNICODE), OT(HIR_TYPE_OBJECT)}},
    /* FormatWithSpec                           */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* GetAIter                                 */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* GetANext                                 */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* GetIter                                  */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* GetLength                                */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* GetSecondOutput                          */ {1, {OT(HIR_TYPE_TOP)}},
    /* GetTuple                                 */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* Guard                                    */ {1, {OC(HIR_CONSTRAINT_kOptObjectOrCIntOrCBool)}},
    /* GuardIs                                  */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* GuardType                                */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* HintType                                 */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* ImportFrom                               */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* ImportName                               */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_LONG)}},
    /* InitFrameCellVars                        */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* InPlaceOp                                */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* Incref                                   */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* IndexUnbox                               */ {1, {OT(HIR_TYPE_LONG)}},
    /* InitialYield                             */ {0, {{0}}},
    /* IntBinaryOp                              */ {2, {OC(HIR_CONSTRAINT_kMatchAllAsCInt), OC(HIR_CONSTRAINT_kMatchAllAsCInt)}},
    /* PrimitiveBoxBool                         */ {1, {OT(HIR_TYPE_CBOOL)}},
    /* PrimitiveBox                             */ {1, {OT(HIR_TYPE_PRIMITIVE)}},
    /* PrimitiveCompare                         */ {0, {{0}}},
    /* IntConvert                               */ {1, {OT(HIR_TYPE_PRIMITIVE)}},
    /* PrimitiveUnaryOp                         */ {1, {OT(HIR_TYPE_PRIMITIVE)}},
    /* PrimitiveUnbox                           */ {0, {{0}}},
    /* InvokeIterNext                           */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* IsInstance                               */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_TYPE)}},
    /* InvokeStaticFunction                     */ {1, {OT(HIR_TYPE_TOP)}},
    /* IsNegativeAndErrOccurred                 */ {1, {OT(HIR_TYPE_CINT)}},
    /* IsTruthy                                 */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* ListAppend                               */ {2, {OC(HIR_CONSTRAINT_kListOrChkList), OT(HIR_TYPE_OPTOBJECT)}},
    /* ListExtend                               */ {2, {OC(HIR_CONSTRAINT_kListOrChkList), OT(HIR_TYPE_OBJECT)}},
    /* LoadArrayItem                            */ {3, {OC(HIR_CONSTRAINT_kTupleExactOrCPtr), OT(HIR_TYPE_CINT), OT(HIR_TYPE_OPTOBJECT)}},
    /* LoadFieldAddress                         */ {2, {OT(HIR_TYPE_OPTOBJECT), OT(HIR_TYPE_CINT64)}},
    /* LoadArg                                  */ {0, {{0}}},
    /* LoadAttr                                 */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadAttrCached                           */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadAttrSpecial                          */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadAttrSuper                            */ {3, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_TYPE), OT(HIR_TYPE_OBJECT)}},
    /* LoadCellItem                             */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* LoadConst                                */ {0, {{0}}},
    /* LoadCurrentFunc                          */ {0, {{0}}},
    /* LoadFrame                                */ {0, {{0}}},
    /* LoadEvalBreaker                          */ {0, {{0}}},
    /* AtQuiescentState                         */ {0, {{0}}},
    /* LoadField                                */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* LoadFunctionIndirect                     */ {0, {{0}}},
    /* LoadGlobalCached                         */ {0, {{0}}},
    /* LoadGlobal                               */ {0, {{0}}},
    /* LoadMethod                               */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadMethodCached                         */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadModuleAttrCached                     */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadModuleMethodCached                   */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadMethodSuper                          */ {3, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_TYPE), OT(HIR_TYPE_OBJECT)}},
    /* LoadSpecial                              */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* LoadSplitDictItem                        */ {1, {OT(HIR_TYPE_DICT)}},
    /* LoadTupleItem                            */ {1, {OT(HIR_TYPE_TUPLE)}},
    /* LoadTypeAttrCacheEntryType               */ {0, {{0}}},
    /* LoadTypeAttrCacheEntryValue              */ {0, {{0}}},
    /* LoadTypeMethodCacheEntryType             */ {0, {{0}}},
    /* LoadTypeMethodCacheEntryValue            */ {1, {OT(HIR_TYPE_TYPE)}},
    /* LoadVarObjectSize                        */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* LongCompare                              */ {2, {OT(HIR_TYPE_LONGEXACT), OT(HIR_TYPE_LONGEXACT)}},
    /* LongBinaryOp                             */ {2, {OT(HIR_TYPE_LONGEXACT), OT(HIR_TYPE_LONGEXACT)}},
    /* LongInPlaceOp                            */ {2, {OT(HIR_TYPE_LONGEXACT), OT(HIR_TYPE_LONGEXACT)}},
    /* MakeCheckedDict                          */ {0, {{0}}},
    /* MakeCheckedList                          */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* MakeCell                                 */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* MakeDict                                 */ {0, {{0}}},
    /* MakeFunction                             */ {2, {OT(HIR_TYPE_CODE), OT(HIR_TYPE_OPTOBJECT)}},
    /* MakeList                                 */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* MakeTuple                                */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* MakeSet                                  */ {0, {{0}}},
    /* MakeTupleFromList                        */ {1, {OT(HIR_TYPE_LIST)}},
    /* MatchClass                               */ {4, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_CUINT64), OT(HIR_TYPE_OBJECT)}},
    /* MatchKeys                                */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* MergeSetUnpack                           */ {2, {OT(HIR_TYPE_SET), OT(HIR_TYPE_OBJECT)}},
    /* Phi                                      */ {1, {OT(HIR_TYPE_TOP)}},
    /* Raise                                    */ {0, {{0}}},
    /* RaiseStatic                              */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* RaiseAwaitableError                      */ {1, {OT(HIR_TYPE_TYPE)}},
    /* RefineType                               */ {1, {OT(HIR_TYPE_TOP)}},
    /* Return                                   */ {0, {{0}}},
    /* RunPeriodicTasks                         */ {0, {{0}}},
    /* Send                                     */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* SetCellItem                              */ {3, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OPTOBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* SetCurrentAwaiter                        */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* SetDictItem                              */ {3, {OC(HIR_CONSTRAINT_kDictOrChkDict), OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* SetFunctionAttr                          */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_FUNC)}},
    /* SetSetItem                               */ {2, {OT(HIR_TYPE_SET), OT(HIR_TYPE_OBJECT)}},
    /* SetUpdate                                */ {2, {OT(HIR_TYPE_SET), OT(HIR_TYPE_OBJECT)}},
    /* Snapshot                                 */ {0, {{0}}},
    /* StealCellItem                            */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* SwapCellItem                             */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* StoreArrayItem                           */ {4, {OT(HIR_TYPE_CPTR), OT(HIR_TYPE_CINT), OT(HIR_TYPE_TOP), OT(HIR_TYPE_OBJECT)}},
    /* StoreAttr                                */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* StoreAttrCached                          */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT)}},
    /* StoreField                               */ {3, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_TOP), OT(HIR_TYPE_OPTOBJECT)}},
    /* StoreSubscr                              */ {3, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* TpAlloc                                  */ {0, {{0}}},
    /* UnaryOp                                  */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* UnicodeCompare                           */ {2, {OT(HIR_TYPE_UNICODEEXACT), OT(HIR_TYPE_UNICODEEXACT)}},
    /* UnicodeConcat                            */ {2, {OT(HIR_TYPE_UNICODEEXACT), OT(HIR_TYPE_UNICODEEXACT)}},
    /* UnicodeRepeat                            */ {2, {OT(HIR_TYPE_UNICODEEXACT), OT(HIR_TYPE_CINT64)}},
    /* UnicodeSubscr                            */ {2, {OT(HIR_TYPE_UNICODEEXACT), OT(HIR_TYPE_CINT64)}},
    /* UnpackExToTuple                          */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* Unreachable                              */ {0, {{0}}},
    /* UpdatePrevInstr                          */ {0, {{0}}},
    /* UseType                                  */ {0, {{0}}},
    /* VectorCall                               */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* WaitHandleLoadCoroOrResult               */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* WaitHandleLoadWaiter                     */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* WaitHandleRelease                        */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* XDecref                                  */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* XIncref                                  */ {1, {OT(HIR_TYPE_OPTOBJECT)}},
    /* YieldAndYieldFrom                        */ {2, {OT(HIR_TYPE_OPTOBJECT), OT(HIR_TYPE_OBJECT)}},
    /* YieldFrom                                */ {2, {OT(HIR_TYPE_OBJECT), OT(HIR_TYPE_OPTOBJECT)}},
    /* YieldFromHandleStopAsyncIteration        */ {1, {OT(HIR_TYPE_OBJECT)}},
    /* YieldValue                               */ {1, {OT(HIR_TYPE_OBJECT)}},
};

#undef OT
#undef OC

const HirOpcodeOperandInfo *hir_operand_type_get_info(int opcode) {
    if (opcode < 0 || opcode >= HIR_OP_COUNT) {
        return NULL;
    }
    return &operand_type_table[opcode];
}
