/* Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Static metadata table for HIR instruction opcodes.
 * T2-A: Phase 3D Tier 2 — replaces InstrT<> template metadata.
 *
 * Data extracted from hir.h InstrT<> template parameters:
 * - fixed_arity: Operands<N> → N, OperandsAny → -1
 * - has_output: HasOutput tag presence
 * - is_deopt_base: inherits from DeoptBase
 * - is_terminator: IsTerminator() returns true
 */

#include "cinderx/Jit/hir/hir_instr_info_c.h"

/* Table entries in FOREACH_OPCODE order (must match hir_ops.h enum) */
/* {name, arity, output, deopt, term, replayable} */
static const HirInstrInfo hir_instr_info_table[] = {
    {"Assign",                          1,  1, 0, 0, 1},
    {"BatchDecref",                    -1,  0, 0, 0, 0},
    {"BeginInlinedFunction",            0,  0, 0, 0, 0},
    {"BinaryOp",                        2,  1, 1, 0, 0},
    {"BitCast",                         1,  1, 0, 0, 1},
    {"Branch",                          0,  0, 0, 1, 0},
    {"BuildSlice",                     -1,  1, 1, 0, 0},
    {"BuildString",                    -1,  1, 1, 0, 1},
    {"BuildInterpolation",              3,  1, 1, 0, 0},
    {"BuildTemplate",                   2,  1, 1, 0, 0},
    {"CallCFunc",                      -1,  1, 0, 0, 0},
    {"CallEx",                          3,  1, 1, 0, 0},
    {"CallIntrinsic",                  -1,  1, 0, 0, 0},
    {"CallInd",                        -1,  1, 1, 0, 0},
    {"CallMethod",                     -1,  1, 1, 0, 0},
    {"CallStatic",                     -1,  1, 0, 0, 0},
    {"CallStaticRetVoid",              -1,  0, 0, 0, 0},
    {"Cast",                            1,  1, 1, 0, 1},
    {"CheckSequenceBounds",             2,  1, 1, 0, 1},
    {"CheckErrOccurred",                0,  0, 1, 0, 1},
    {"CheckExc",                        1,  1, 1, 0, 1},
    {"CheckNeg",                        1,  1, 1, 0, 1},
    {"CheckVar",                        1,  1, 1, 0, 1},
    {"CheckFreevar",                    1,  1, 1, 0, 1},
    {"CheckField",                      1,  1, 1, 0, 1},
    {"CIntToCBool",                     1,  1, 0, 0, 1},
    {"Compare",                         2,  1, 1, 0, 0},
    {"CompareBool",                     2,  1, 1, 0, 0},
    {"ConvertValue",                    1,  1, 1, 0, 0},
    {"CopyDictWithoutKeys",             2,  1, 1, 0, 0},
    {"CondBranch",                      1,  0, 0, 1, 0},
    {"CondBranchIterNotDone",           1,  0, 0, 1, 0},
    {"CondBranchCheckType",             1,  0, 0, 1, 0},
    {"Decref",                          1,  0, 0, 0, 0},
    {"DeleteAttr",                      1,  0, 1, 0, 0},
    {"DeleteSubscr",                    2,  0, 1, 0, 0},
    {"Deopt",                           0,  0, 1, 1, 0},
    {"DeoptPatchpoint",                 0,  0, 1, 0, 0},
    {"DictMerge",                       3,  1, 1, 0, 0},
    {"DictSubscr",                      2,  1, 1, 0, 0},
    {"DictUpdate",                      2,  1, 1, 0, 0},
    {"DoubleBinaryOp",                  2,  1, 0, 0, 1},
    {"EagerImportName",                 2,  1, 1, 0, 0},
    {"EndInlinedFunction",              0,  0, 0, 0, 0},
    {"FillTypeAttrCache",               1,  1, 1, 0, 0},
    {"FillTypeMethodCache",             1,  1, 1, 0, 0},
    {"FloatBinaryOp",                   2,  1, 1, 0, 0},
    {"FloatCompare",                    2,  1, 0, 0, 1},
    {"FormatValue",                     2,  1, 1, 0, 1},
    {"FormatWithSpec",                  2,  1, 1, 0, 1},
    {"GetAIter",                        1,  1, 1, 0, 0},
    {"GetANext",                        1,  1, 1, 0, 0},
    {"GetIter",                         1,  1, 1, 0, 0},
    {"GetLength",                       1,  1, 1, 0, 0},
    {"GetSecondOutput",                 1,  1, 0, 0, 1},
    {"GetTuple",                        1,  1, 1, 0, 0},
    {"Guard",                           1,  0, 1, 0, 1},
    {"GuardIs",                         1,  1, 1, 0, 1},
    {"GuardType",                       1,  1, 1, 0, 1},
    {"HintType",                       -1,  0, 0, 0, 1},
    {"ImportFrom",                      1,  1, 1, 0, 0},
    {"ImportName",                      2,  1, 1, 0, 0},
    {"InitFrameCellVars",               1,  0, 0, 0, 0},
    {"InPlaceOp",                       2,  1, 1, 0, 0},
    {"Incref",                          1,  0, 0, 0, 0},
    {"IndexUnbox",                      1,  1, 0, 0, 1},
    {"InitialYield",                    0,  1, 1, 0, 0},
    {"IntBinaryOp",                     2,  1, 0, 0, 1},
    {"PrimitiveBoxBool",                1,  1, 0, 0, 1},
    {"PrimitiveBox",                    1,  1, 1, 0, 1},
    {"PrimitiveCompare",                2,  1, 0, 0, 1},
    {"IntConvert",                      1,  1, 0, 0, 1},
    {"PrimitiveUnaryOp",                1,  1, 0, 0, 1},
    {"PrimitiveUnbox",                  1,  1, 0, 0, 1},
    {"InvokeIterNext",                  1,  1, 1, 0, 0},
    {"IsInstance",                       2,  1, 1, 0, 0},
    {"InvokeStaticFunction",           -1,  1, 1, 0, 0},
    {"IsNegativeAndErrOccurred",        1,  1, 1, 0, 1},
    {"IsTruthy",                        1,  1, 1, 0, 0},
    {"ListAppend",                      2,  1, 1, 0, 0},
    {"ListExtend",                      2,  1, 1, 0, 0},
    {"LoadArrayItem",                   3,  1, 0, 0, 1},
    {"LoadFieldAddress",                2,  1, 0, 0, 1},
    {"LoadArg",                         0,  1, 0, 0, 1},
    {"LoadAttr",                        1,  1, 1, 0, 0},
    {"LoadAttrCached",                  1,  1, 1, 0, 0},
    {"LoadAttrSpecial",                 1,  1, 1, 0, 0},
    {"LoadAttrSuper",                   3,  1, 1, 0, 0},
    {"LoadCellItem",                    1,  1, 0, 0, 1},
    {"LoadConst",                       0,  1, 0, 0, 1},
    {"LoadCurrentFunc",                 0,  1, 0, 0, 1},
    {"LoadFrame",                       0,  0, 0, 0, 1},
    {"LoadEvalBreaker",                 0,  1, 0, 0, 1},
    {"AtQuiescentState",                0,  0, 0, 0, 1},
    {"LoadField",                       1,  1, 0, 0, 1},
    {"LoadFunctionIndirect",            0,  1, 1, 0, 1},
    {"LoadGlobalCached",                0,  1, 0, 0, 1},
    {"LoadGlobal",                      0,  1, 1, 0, 0},
    {"LoadMethod",                      1,  1, 1, 0, 0},
    {"LoadMethodCached",                1,  1, 1, 0, 0},
    {"LoadModuleAttrCached",            1,  1, 1, 0, 0},
    {"LoadModuleMethodCached",          1,  1, 1, 0, 0},
    {"LoadMethodSuper",                 3,  1, 1, 0, 0},
    {"LoadSpecial",                     1,  1, 1, 0, 0},
    {"LoadSplitDictItem",               1,  1, 0, 0, 1},
    {"LoadTupleItem",                   1,  1, 0, 0, 1},
    {"LoadTypeAttrCacheEntryType",      0,  1, 0, 0, 1},
    {"LoadTypeAttrCacheEntryValue",     0,  1, 0, 0, 1},
    {"LoadTypeMethodCacheEntryType",    0,  1, 0, 0, 1},
    {"LoadTypeMethodCacheEntryValue",   1,  1, 0, 0, 1},
    {"LoadVarObjectSize",               1,  1, 0, 0, 1},
    {"LongCompare",                     2,  1, 0, 0, 1},
    {"LongBinaryOp",                    2,  1, 1, 0, 0},
    {"LongInPlaceOp",                   2,  1, 1, 0, 0},
    {"MakeCheckedDict",                 0,  1, 1, 0, 0},
    {"MakeCheckedList",                -1,  1, 1, 0, 0},
    {"MakeCell",                        1,  1, 1, 0, 0},
    {"MakeDict",                        0,  1, 1, 0, 0},
    {"MakeFunction",                    2,  1, 1, 0, 0},
    {"MakeList",                       -1,  1, 1, 0, 0},
    {"MakeTuple",                      -1,  1, 1, 0, 0},
    {"MakeSet",                         0,  1, 1, 0, 0},
    {"MakeTupleFromList",               1,  1, 1, 0, 0},
    {"MatchClass",                      4,  1, 0, 0, 0},
    {"MatchKeys",                       2,  1, 1, 0, 0},
    {"MergeSetUnpack",                  2,  1, 1, 0, 0},
    {"Phi",                            -1,  1, 0, 0, 0},
    {"Raise",                           0,  0, 1, 1, 1},
    {"RaiseStatic",                    -1,  0, 1, 1, 1},
    {"RaiseAwaitableError",             1,  0, 1, 1, 0},
    {"RefineType",                      1,  1, 0, 0, 1},
    {"Return",                          1,  0, 0, 1, 0},
    {"RunPeriodicTasks",                0,  1, 1, 0, 0},
    {"Send",                            2,  1, 1, 0, 0},
    {"SetCellItem",                     3,  0, 0, 0, 0},
    {"SetCurrentAwaiter",               1,  0, 0, 0, 0},
    {"SetDictItem",                     3,  1, 1, 0, 0},
    {"SetFunctionAttr",                 2,  0, 0, 0, 0},
    {"SetSetItem",                      2,  1, 1, 0, 0},
    {"SetUpdate",                       2,  1, 1, 0, 0},
    {"Snapshot",                         0,  0, 0, 0, 0},
    {"StealCellItem",                   1,  1, 0, 0, 1},
    {"SwapCellItem",                    2,  1, 0, 0, 0},
    {"StoreArrayItem",                  4,  0, 0, 0, 0},
    {"StoreAttr",                       2,  0, 1, 0, 0},
    {"StoreAttrCached",                 2,  0, 1, 0, 0},
    {"StoreField",                      3,  0, 0, 0, 0},
    {"StoreSubscr",                     3,  0, 1, 0, 0},
    {"TpAlloc",                         0,  1, 1, 0, 0},
    {"UnaryOp",                         1,  1, 1, 0, 0},
    {"UnicodeCompare",                  2,  1, 0, 0, 1},
    {"UnicodeConcat",                   2,  1, 1, 0, 1},
    {"UnicodeRepeat",                   2,  1, 1, 0, 0},
    {"UnicodeSubscr",                   2,  1, 1, 0, 1},
    {"UnpackExToTuple",                 1,  1, 1, 0, 0},
    {"Unreachable",                     0,  0, 0, 1, 0},
    {"UpdatePrevInstr",                 0,  0, 0, 0, 1},
    {"UseType",                         1,  0, 0, 0, 1},
    {"VectorCall",                     -1,  1, 1, 0, 0},
    {"WaitHandleLoadCoroOrResult",      1,  1, 0, 0, 1},
    {"WaitHandleLoadWaiter",            1,  1, 0, 0, 1},
    {"WaitHandleRelease",               1,  0, 0, 0, 0},
    {"XDecref",                         1,  0, 0, 0, 0},
    {"XIncref",                         1,  0, 0, 0, 0},
    {"YieldAndYieldFrom",               2,  1, 1, 0, 0},
    {"YieldFrom",                       2,  1, 1, 0, 0},
    {"YieldFromHandleStopAsyncIteration", 2, 1, 1, 0, 0},
    {"YieldValue",                      1,  1, 1, 0, 0},
};

#define HIR_INSTR_INFO_COUNT \
    (sizeof(hir_instr_info_table) / sizeof(hir_instr_info_table[0]))

const HirInstrInfo *hir_instr_get_info(int opcode) {
    if (opcode < 0 || (size_t)opcode >= HIR_INSTR_INFO_COUNT) {
        return &hir_instr_info_table[0]; /* fallback to Assign */
    }
    return &hir_instr_info_table[opcode];
}
